blank_issues_enabled: false
template:
  - name: Bug Report
    file: bug_report.md
    title: "[Bug] "
    labels: [bug]
  - name: Feature Request
    file: feature_request.md
    title: "[Feature] "
    labels: [enhancement] 